apiVersion: v1
kind: Secret
metadata:
  name: relayer-secrets
type: Opaque
stringData:
  RELAYER_PK: {{ .Values.relayer.secrets.RELAYER_PK | quote }}
  VENUE_HMAC_KEY: {{ .Values.relayer.secrets.VENUE_HMAC_KEY | quote }}
  API_KEYS_CSV: {{ .Values.relayer.secrets.API_KEYS_CSV | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pinner-secrets
type: Opaque
stringData:
  PINNING_JWT: {{ .Values.pinner.secrets.PINNING_JWT | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secrets
type: Opaque
stringData:
  password: {{ .Values.postgres.password | quote }}
